### ISSUE TITLE
[Bug?] 評価の際に実行時エラーが発生している

### ISSUE THREAD

**Issue by otokunaga2** [horiso0921/Platform#1]
お世話になっております。
ツールを公開して頂きありがとうございます。
弊所で作成したモデルの評価にこちらのプログラムを利用させてもらったところ、
以下のようなエラーが発生してしまいました。
本件対応方法などありましたら、教えて頂けますと非常に助かります。
※newuttのデータを調べたところ入力した文字列がそのまま渡されているようでした。
そのほか調査に必要な情報がありましたら、適宜ご協力できると思います。
宜しくお願いいたします。

```
ontent (Type end to end) >> 02_近所の名所[SEP]生きているへびを見たことがあるんですか？
Traceback (most recent call last):
  File "interactive.py", line 69, in <module>
    main()
  File "interactive.py", line 66, in main
    test(logger, parser, args)
  File "interactive.py", line 51, in test
    ret = favot.execute(line)
  File "/content/platform/scripts/model.py", line 181, in execute
    ret = self._execute(uttr, mode=mode)
  File "/content/platform/scripts/model.py", line 204, in _execute
    self.make_input_func(SPK2, uttr, mode=mode),
  File "/content/platform/scripts/model.py", line 481, in make_input
    contexts = newutt["data"]
TypeError: string indices must be integers`
```

**Comment by horiso0921** [comment]
ありがとうございます．
こちらは mainブランチでの実行ということでよろしいでしょうか？

**Comment by horiso0921** [comment]
よろしければ実行している ディレクトリの最新commitIDを教えていただけますと幸いです

**Comment by otokunaga2** [comment]
@horiso0921 
返信遅くなってしまいました。
ご確認ありがとうございます。

> こちらは mainブランチでの実行ということでよろしいでしょうか？

はい、mainブランチになります。

> よろしければ実行している ディレクトリの最新commitIDを教えていただけますと幸いです

以下の通りです。
※Google Colabで実行しており、基本的には最新版をクローンして
利用させてもらっています。
01f92bc5040afcb81f710081e499e1f66bbf021b 

また、別件ですが実行時にインデントが崩れている箇所が見受けられました。
以下の行ですが、空白スペースが1つ多い気がします。。。
そちらも合わせてご確認頂けますと幸いです。
https://github.com/horiso0921/Platform/blob/main/scripts/model.py#L470

**Comment by horiso0921** [comment]
@otokunaga2 
大変遅くなり申し訳ありません．
interactiveにコンソール上で行う際の挙動を考慮していませんでした．

修正パッチを最新のmainブランチに適応したため，pullしていただければ起動すると思われます．

また何かありましたらよろしくお願いします．

**Comment by otokunaga2** [comment]
@horiso0921 
ご対応ありがとうございました！  
無事に動作させることが出来ました。   
イシューの方もクローズさせて頂きました。
